server:
  port: 8085

spring:
  application:
    name: zuul-proxy

  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

zuul:
  routes:
    CLIENT1:
      service-id: eureka-client-app1
      path: /app1/*
      strip-prefix: false
    CLIENT2:
      service-id: eureka-client-app2
      path: /app2/*
      strip-prefix: true

## spring actuator endpoints

management:
  endpoints:
    web:
      exposure:
        include: 
          - "*"   
      
